### ISSUE TITLE
Snowpack update breaks plugin.js

### ISSUE THREAD

**Issue by wforney** [brandonseydel/aurelia-snowpack#1]
While this works as is, if you update snowpack to the latest the plugin.js no longer works. Seems a few things changed.

**Comment by brandonseydel** [comment]
Good to know thanks!

**Comment by zhanglongyu** [comment]
Any news on this? I want to use snowpack with aurelia,finally found this plugin to solve the @customElement issue.will you fix this issue and maintain the plugin? or is there any solution to use snowpack with aurelia easily? Thanks.

**Comment by brandonseydel** [comment]
I will be revisting this now as Aurelia 2 is hitting alpha.

**Comment by PraveenGandhi** [comment]
Any plans to update as Aurelia 2 alpha is released?

**Comment by brandonseydel** [comment]
Yes I was away from home for some time and now back.  I will be updating this soon.

**Comment by PraveenGandhi** [comment]
I tried to make it work by myself https://github.com/PraveenGandhi/aurelia-snowpack-plugin

but failing with errors

![image](https://user-images.githubusercontent.com/1082966/113466650-10386c00-945b-11eb-9d87-bc6d53520e8d.png)

**Comment by brandonseydel** [comment]
This is fixed now.
